[jackrabbit-ops]
square = 
long = 

[jadbio]
square = 
long = 

[jaeves]
square = 
long = 

[jagir]
square = 
long = 

[jam]
square = 
long = 

[jamie]
square = 
long = 

[jamorphosia]
square = 
long = 

[jane-ai-assistant]
square = 
long = 

[japandailynews]
square = 
long = 

[jaq-n-jil]
square = 
long = 

[jargonnay]
square = 
long = 

[jarside]
square = 
long = 

[jarvis-ai]
square = 
long = 

[jarvis-ai-assistant]
square = 
long = 

[jarvis-app]
square = 
long = 

[jarvis-hugginggpt]
square = 
long = 

[jarvis-tel]
square = 
long = 

[jason-ai]
square = 
long = 

[jaydee]
square = 
long = 

[jazzup]
square = 
long = 

[jd-aid]
square = 
long = 

[jd-generator]
square = 
long = 

[jeda-ai]
square = 
long = 

[jedi-gpt]
square = 
long = 

[jeeves]
square = 
long = 

[jeffrey-c-lavie]
square = 
long = 

[jema]
square = 
long = 

[jenni]
square = 
long = 

[jessica-by-betterspeech]
square = 
long = 

[jester-ai-caption-writer]
square = 
long = 

[jet-cut-ready]
square = 
long = 

[jetbrains-ide-plugin]
square = 
long = 

[jetpack]
square = 
long = 

[jife]
square = 
long = 

[jimaku]
square = 
long = 

[jimmygpt]
square = 
long = 

[jinachat]
square = 
long = 

[jinnee]
square = 
long = 

[jinni]
square = 
long = 

[jiragpt]
square = 
long = 

[jit-codes]
square = 
long = 

[job-interview-ai]
square = 
long = 

[jobcopy]
square = 
long = 

[jobdescriptiongenerator]
square = 
long = 

[jobed]
square = 
long = 

[jobinterview-coach]
square = 
long = 

[joblens]
square = 
long = 

[jobmind]
square = 
long = 

[jobprescreen]
square = 
long = 

[jobs-scout]
square = 
long = 

[jobscan]
square = 
long = 

[jobsearch-coach]
square = 
long = 

[jobtitlesai]
square = 
long = 

[john-carmack-insights]
square = 
long = 

[joi-ai]
square = 
long = 

[joi-ai-girlfriend-18]
square = 
long = 

[jokelub]
square = 
long = 

[jon-quote-to-invoice]
square = 
long = 

[jot]
square = 
long = 

[jotgenius]
square = 
long = 

[jotpro]
square = 
long = 

[jotters-pad]
square = 
long = 

[jottery]
square = 
long = 

[jounce]
square = 
long = 

[journalist-ai]
square = 
long = 

[journeai]
square = 
long = 

[journey-io]
square = 
long = 

[journey-mixer]
square = 
long = 

[journeyplan]
square = 
long = 

[joyai]
square = 
long = 

[joypanner]
square = 
long = 

[joyplanet]
square = 
long = 

[jpghd]
square = 
long = 

[jpgrm]
square = 
long = 

[jpt]
square = 
long = 

[js2ts]
square = 
long = 

[json-data]
square = 
long = 

[jua]
square = 
long = 

[judeai]
square = 
long = 

[judichat]
square = 
long = 

[juicebox-ai]
square = 
long = 

[juji]
square = 
long = 

[jukegpt]
square = 
long = 

[jumble-journal]
square = 
long = 

[june-ai]
square = 
long = 

[jungle-ai]
square = 
long = 

[junia]
square = 
long = 

[junior]
square = 
long = 

[jupitrr]
square = 
long = 

[jurny]
square = 
long = 

[jusi]
square = 
long = 

[just-story-it]
square = 
long = 

[justaichat]
square = 
long = 

[justfive]
square = 
long = 

[jagodaai]
square = 
long = 

[jan]
square = 
long = 

[jasper-ai]
square = 
long = 

[jellypod]
square = 
long = 

[jobwizard]
square = 
long = 

[jumpboost]
square = 
long = 

[juri-flow]
square = 
long = 

[just-prompts]
square = 
long = 

[justblog]
square = 
long = 

[justcomment]
square = 
long = 

[justvise]
square = 
long = 

[just-command]
square = 
long = 

[justlearn]
square = 
long = 

[jobs-chat]
square = 
long = 

[junggpt]
square = 
long = 

[justapi]
square = 
long = 

[jochem]
square = 
long = 

[juno]
square = 
long = 

[julius]
square = 
long = 

[jetbrains]
square = 
long = 

[job-hunt-mode]
square = 
long = 

[just-think]
square = 
long = 

