[xploro]
square = 
long = 

[xno]
square = 
long = 

[xactions]
square = 
long = 

[xpeacho]
square = 
long = 

[xata]
square = 
long = 

[xenonstack]
square = 
long = 

[xence-ai]
square = 
long = 

[xagent]
square = 
long = 

[x-minus]
square = 
long = 

[xnote]
square = 
long = 

[xero]
square = 
long = 

[xpath-labs]
square = 
long = 

[xo-analytics]
square = 
long = 

[x3-regem]
square = 
long = 

[xboard]
square = 
long = 

[xcodechatgpt]
square = 
long = 

[xor-ai]
square = 
long = 

[xbuddy]
square = 
long = 

[xinva]
square = 
long = 

[xamtac]
square = 
long = 

[xturing]
square = 
long = 

[xipher]
square = 
long = 

[xpert]
square = 
long = 

[xembly]
square = 
long = 

[ximilar]
square = 
long = 

[xmind]
square = 
long = 

[xprt]
square = 
long = 

[xobin-ai-evaluate]
square = 
long = 

[xploro]
square = 
long = 

[xno]
square = 
long = 

[xactions]
square = 
long = 

[xpeacho]
square = 
long = 

[xata]
square = 
long = 

[xenonstack]
square = 
long = 

[xence-ai]
square = 
long = 

[xagent]
square = 
long = 

[x-minus]
square = 
long = 

[xnote]
square = 
long = 

[xero]
square = 
long = 

[xpath-labs]
square = 
long = 

[xo-analytics]
square = 
long = 

[x3-regem]
square = 
long = 

[xboard]
square = 
long = 

[xcodechatgpt]
square = 
long = 

[xor-ai]
square = 
long = 

[xbuddy]
square = 
long = 

[xinva]
square = 
long = 

[xamtac]
square = 
long = 

[xturing]
square = 
long = 

[xipher]
square = 
long = 

[xpert]
square = 
long = 

[xembly]
square = 
long = 

[ximilar]
square = 
long = 

[xmind]
square = 
long = 

[xprt]
square = 
long = 

[xobin-ai-evaluate]
square = 
long = 

