[labelbox]
square = 
long = 

[labelgpt]
square = 
long = 

[laborai]
square = 
long = 

[laika]
square = 
long = 

[laketool]
square = 
long = 

[lalal]
square = 
long = 

[lalamu]
square = 
long = 

[lamdai-playground]
square = 
long = 

[lamini]
square = 
long = 

[lampbuilder]
square = 
long = 

[lampi-ai]
square = 
long = 

[lancey]
square = 
long = 

[lander]
square = 
long = 

[landing-ai]
square = 
long = 

[landing-page-copy]
square = 
long = 

[landr]
square = 
long = 

[landrific]
square = 
long = 

[langame-card-game]
square = 
long = 

[langchain]
square = 
long = 

[langchats]
square = 
long = 

[langdock]
square = 
long = 

[langgpt]
square = 
long = 

[langmob]
square = 
long = 

[langotalk]
square = 
long = 

[langs]
square = 
long = 

[langsmith]
square = 
long = 

[langsync]
square = 
long = 

[langtail]
square = 
long = 

[language-reactor]
square = 
long = 

[languagemate]
square = 
long = 

[languagepro]
square = 
long = 

[languagetool]
square = 
long = 

[languify]
square = 
long = 

[larry-the-elf]
square = 
long = 

[lasso-ai]
square = 
long = 

[latch]
square = 
long = 

[lately-ai]
square = 
long = 

[latent-workers]
square = 
long = 

[latentspace]
square = 
long = 

[latitude]
square = 
long = 

[latte]
square = 
long = 

[lavender]
square = 
long = 

[lavo]
square = 
long = 

[lawmate]
square = 
long = 

[lawrie]
square = 
long = 

[laxis-2-0]
square = 
long = 

[layer-ai]
square = 
long = 

[layer-ai-research-assistant]
square = 
long = 

[layerbrain]
square = 
long = 

[layernext]
square = 
long = 

[layerup]
square = 
long = 

[layerz]
square = 
long = 

[layla]
square = 
long = 

[layman-law]
square = 
long = 

[layup]
square = 
long = 

[lazi-tech]
square = 
long = 

[lazy-cards]
square = 
long = 

[lazyapply]
square = 
long = 

[lazynotes]
square = 
long = 

[lazyreply]
square = 
long = 

[leaddelta]
square = 
long = 

[leadflow]
square = 
long = 

[leadiq]
square = 
long = 

[leadmaster]
square = 
long = 

[leadscripts]
square = 
long = 

[leadsourcing]
square = 
long = 

[leaf]
square = 
long = 

[lean-canvas]
square = 
long = 

[lean-canvas-ai]
square = 
long = 

[leanbe]
square = 
long = 

[leap]
square = 
long = 

[learity]
square = 
long = 

[learngpt]
square = 
long = 

[learnlingo]
square = 
long = 

[learnplan]
square = 
long = 

[learnsmarter]
square = 
long = 

[learnt]
square = 
long = 

[leaselens]
square = 
long = 

[lebesgue]
square = 
long = 

[lecture-mate]
square = 
long = 

[ledgerbox]
square = 
long = 

[leeai]
square = 
long = 

[leelo]
square = 
long = 

[leena-ai]
square = 
long = 

[leet-resumes]
square = 
long = 

[leeta]
square = 
long = 

[leeway]
square = 
long = 

[leexi]
square = 
long = 

[leftovers-ai]
square = 
long = 

[legacy-ai]
square = 
long = 

[legait]
square = 
long = 

[legal-ai]
square = 
long = 

[legal-assist-ai]
square = 
long = 

[legalese-decoder]
square = 
long = 

[legalgraph]
square = 
long = 

[legaliser]
square = 
long = 

[legalnow]
square = 
long = 

[legalysis]
square = 
long = 

[legalyze]
square = 
long = 

[legit-startups]
square = 
long = 

[legitt-ai-contract-generator]
square = 
long = 

[legoai]
square = 
long = 

[leia]
square = 
long = 

[lejrr]
square = 
long = 

[lek]
square = 
long = 

[lekhak]
square = 
long = 

[lemmy]
square = 
long = 

[lemonado]
square = 
long = 

[lemonaid-music]
square = 
long = 

[lemonfox]
square = 
long = 

[lemonstocks]
square = 
long = 

[lens-studio]
square = 
long = 

[lensa-ai]
square = 
long = 

[lensai]
square = 
long = 

[lensco]
square = 
long = 

[lensquery]
square = 
long = 

[lensto]
square = 
long = 

[leny]
square = 
long = 

[leo]
square = 
long = 

[leonardo]
square = 
long = 

[lepton]
square = 
long = 

[lesseffort]
square = 
long = 

[lessonplans]
square = 
long = 

[letsask]
square = 
long = 

[letsview-chat]
square = 
long = 

[letterdrop]
square = 
long = 

[lettergram]
square = 
long = 

[letterly-app]
square = 
long = 

[lettermagic]
square = 
long = 

[letternerd]
square = 
long = 

[lettria]
square = 
long = 

[levelfields]
square = 
long = 

[levity]
square = 
long = 

[levytation]
square = 
long = 

[lewk]
square = 
long = 

[lex]
square = 
long = 

[lex-gpt]
square = 
long = 

[lexeme]
square = 
long = 

[lexi]
square = 
long = 

[lexii]
square = 
long = 

[lexy]
square = 
long = 

[lexy-so]
square = 
long = 

[leya-ai]
square = 
long = 

[lia]
square = 
long = 

[liarliar]
square = 
long = 

[libraai]
square = 
long = 

[libraria]
square = 
long = 

[librarian-ai]
square = 
long = 

[lida]
square = 
long = 

[liftlog]
square = 
long = 

[liftoff]
square = 
long = 

[lifty]
square = 
long = 

[liftz]
square = 
long = 

[light]
square = 
long = 

[lightchat]
square = 
long = 

[lightgpt]
square = 
long = 

[lighthouse-internet-guardian]
square = 
long = 

[lightkey]
square = 
long = 

[lightly-ide]
square = 
long = 

[lightning]
square = 
long = 

[lightpdf]
square = 
long = 

[lightrail]
square = 
long = 

[lightricks]
square = 
long = 

[likewise-learn]
square = 
long = 

[lil-gpt-x]
square = 
long = 

[lily]
square = 
long = 

[lilybank]
square = 
long = 

[lime-ai]
square = 
long = 

[limecube]
square = 
long = 

[limeline]
square = 
long = 

[limewire]
square = 
long = 

[lindo]
square = 
long = 

[lindy]
square = 
long = 

[line-21]
square = 
long = 

[liner]
square = 
long = 

[linfo]
square = 
long = 

[lingobo]
square = 
long = 

[lingocoach]
square = 
long = 

[lingostar]
square = 
long = 

[lingosync]
square = 
long = 

[lingtual]
square = 
long = 

[linguabot]
square = 
long = 

[linguai]
square = 
long = 

[lingually]
square = 
long = 

[linguix]
square = 
long = 

[linguo]
square = 
long = 

[lingvanex]
square = 
long = 

[link-whisper]
square = 
long = 

[linkdelta]
square = 
long = 

[linkedin-ai-salesagent]
square = 
long = 

[linkedin-comment-ai]
square = 
long = 

[linkedin-manager]
square = 
long = 

[linkedin-post-spinner]
square = 
long = 

[linkedin-posts-generator]
square = 
long = 

[linkedin-turbo-responder]
square = 
long = 

[linkeo]
square = 
long = 

[linklessgpt]
square = 
long = 

[linkoai]
square = 
long = 

[linkout]
square = 
long = 

[links-briefs]
square = 
long = 

[linnk-the-reading-navigator]
square = 
long = 

[lintrule]
square = 
long = 

[lionvaplus]
square = 
long = 

[lisa]
square = 
long = 

[listen-monster]
square = 
long = 

[listicle-club]
square = 
long = 

[listnr-2-0]
square = 
long = 

[litgrades]
square = 
long = 

[littlecook]
square = 
long = 

[live-captions]
square = 
long = 

[liveperson]
square = 
long = 

[llama2-by-meta]
square = 
long = 

[llama2-chat]
square = 
long = 

[llama2-chat-perplexity]
square = 
long = 

[llama2-perplexity]
square = 
long = 

[llamabot]
square = 
long = 

[llamachat]
square = 
long = 

[llamaindex]
square = 
long = 

[llava]
square = 
long = 

[llime]
square = 
long = 

[llmchess]
square = 
long = 

[llmonitor]
square = 
long = 

[llmstack]
square = 
long = 

[lmnt]
square = 
long = 

[lmql]
square = 
long = 

[lmstudio]
square = 
long = 

[localai]
square = 
long = 

[localbot]
square = 
long = 

[localio-ai]
square = 
long = 

[localy]
square = 
long = 

[locusive]
square = 
long = 

[lodown]
square = 
long = 

[log4u]
square = 
long = 

[logical]
square = 
long = 

[logicballs]
square = 
long = 

[loginllama]
square = 
long = 

[logmeal]
square = 
long = 

[logmeals]
square = 
long = 

[logo-generator]
square = 
long = 

[logo-mockup]
square = 
long = 

[logo-theme-ai]
square = 
long = 

[logoai-image-generator]
square = 
long = 

[logobrainstorm]
square = 
long = 

[logocreatorai]
square = 
long = 

[logodiffusion]
square = 
long = 

[logolept]
square = 
long = 

[logolivery]
square = 
long = 

[logomakerr]
square = 
long = 

[logomaster]
square = 
long = 

[logomeld]
square = 
long = 

[logopicture-ai]
square = 
long = 

[logopony]
square = 
long = 

[logorax]
square = 
long = 

[logoscapes]
square = 
long = 

[logsail]
square = 
long = 

[logwise]
square = 
long = 

[lollib]
square = 
long = 

[lolo]
square = 
long = 

[lomni]
square = 
long = 

[longshot-ai]
square = 
long = 

[loofi]
square = 
long = 

[loofm]
square = 
long = 

[lookbook]
square = 
long = 

[lookmate]
square = 
long = 

[lookr]
square = 
long = 

[lookr-9244]
square = 
long = 

[lookright]
square = 
long = 

[looksounique]
square = 
long = 

[lookup]
square = 
long = 

[lookup-yc]
square = 
long = 

[lookx]
square = 
long = 

[loom-ai]
square = 
long = 

[loopgenius]
square = 
long = 

[loopgpt]
square = 
long = 

[loopin]
square = 
long = 

[loora]
square = 
long = 

[looseleaf]
square = 
long = 

[looti]
square = 
long = 

[lorai]
square = 
long = 

[lorro]
square = 
long = 

[loti]
square = 
long = 

[lotse]
square = 
long = 

[lotus]
square = 
long = 

[loudly]
square = 
long = 

[loukoum]
square = 
long = 

[louply]
square = 
long = 

[love-designing]
square = 
long = 

[lovegenius]
square = 
long = 

[lovelace-studio]
square = 
long = 

[lovelines]
square = 
long = 

[lovespreadsheets]
square = 
long = 

[lovestories]
square = 
long = 

[lovo]
square = 
long = 

[lowtech]
square = 
long = 

[lucid-beads]
square = 
long = 

[lucidfocal]
square = 
long = 

[lucidpic]
square = 
long = 

[lucyai]
square = 
long = 

[lucyd-app]
square = 
long = 

[lude]
square = 
long = 

[ludo]
square = 
long = 

[lugs]
square = 
long = 

[lukew-chat]
square = 
long = 

[lulbot]
square = 
long = 

[lumenvox]
square = 
long = 

[lumiere3d]
square = 
long = 

[lumina-chat]
square = 
long = 

[lumina-tools]
square = 
long = 

[luminaries]
square = 
long = 

[luna]
square = 
long = 

[luna-by-madduck]
square = 
long = 

[luna-speak]
square = 
long = 

[lunabot]
square = 
long = 

[lunally]
square = 
long = 

[lustlab-ai]
square = 
long = 

[luup]
square = 
long = 

[luw-ai]
square = 
long = 

[luxa]
square = 
long = 

[lxi-ai]
square = 
long = 

[lychee]
square = 
long = 

[lykdat]
square = 
long = 

[lyneai]
square = 
long = 

[lyric-studio]
square = 
long = 

[lyricallabs]
square = 
long = 

[lyriclab]
square = 
long = 

[lyro]
square = 
long = 

[lyspeak]
square = 
long = 

[lystinct]
square = 
long = 

[learn-xyz]
square = 
long = 

[learnmate]
square = 
long = 

[link-in-video]
square = 
long = 

[linq-ai]
square = 
long = 

[lipdub]
square = 
long = 

[liro-ai]
square = 
long = 

[lista]
square = 
long = 

[listener]
square = 
long = 

[listpro]
square = 
long = 

[liveform]
square = 
long = 

[lobe-ai]
square = 
long = 

[local-falcon]
square = 
long = 

[logo-rank]
square = 
long = 

[looka]
square = 
long = 

[looki]
square = 
long = 

[lullaby-wonders]
square = 
long = 

[luna-ai]
square = 
long = 

[lutra-ai]
square = 
long = 

[livepolls-mindmaps]
square = 
long = 

[learnery]
square = 
long = 

[luminar-ai]
square = 
long = 

[lorekeeper]
square = 
long = 

[labophase]
square = 
long = 

[lamanote]
square = 
long = 

[linksquares]
square = 
long = 

[literally-anything]
square = 
long = 

[leap-learning]
square = 
long = 

[learningstudioai]
square = 
long = 

[letty]
square = 
long = 

[lexi-app]
square = 
long = 

[leapbox]
square = 
long = 

[lilac]
square = 
long = 

[lazyeyefix]
square = 
long = 

[listening]
square = 
long = 

[lion-browser]
square = 
long = 

[loya]
square = 
long = 

[logoai]
square = 
long = 

[livepolls-slide-generator]
square = 
long = 

[linq-me-up]
square = 
long = 

[launch-teddy]
square = 
long = 

[lyricist]
square = 
long = 

[lumen5]
square = 
long = 

[lingomind]
square = 
long = 

[lumi-tarot]
square = 
long = 

[listingturbo]
square = 
long = 

[lume-ai]
square = 
long = 

[letsenhance]
square = 
long = 

[lowcarbai]
square = 
long = 

[longllama]
square = 
long = 

[llmpeople]
square = 
long = 

[lusion-ai]
square = 
long = 

[lmnt-voicover]
square = 
long = 

[landingsite]
square = 
long = 

[liftsites]
square = 
long = 

[leap-ml]
square = 
long = 

