[g-prompter]
square = 
long = 

[g3d]
square = 
long = 

[gabbygpt]
square = 
long = 

[gait-analyzer]
square = 
long = 

[gajix]
square = 
long = 

[galactic-pulse]
square = 
long = 

[galeby]
square = 
long = 

[galenai]
square = 
long = 

[gali]
square = 
long = 

[game-generator]
square = 
long = 

[gameguide]
square = 
long = 

[gameofpromptsqr]
square = 
long = 

[gamma]
square = 
long = 

[gamma-ai]
square = 
long = 

[gan-ai]
square = 
long = 

[gandhiji]
square = 
long = 

[gapscout]
square = 
long = 

[garden-of-ai]
square = 
long = 

[garson]
square = 
long = 

[gasbyai]
square = 
long = 

[gateai]
square = 
long = 

[gatherly]
square = 
long = 

[gearchain]
square = 
long = 

[geleza]
square = 
long = 

[gem]
square = 
long = 

[gem-tech-finance-news]
square = 
long = 

[gemelo]
square = 
long = 

[gemini-ai]
square = 
long = 

[gemoo]
square = 
long = 

[gems]
square = 
long = 

[gemsouls]
square = 
long = 

[gen-expert]
square = 
long = 

[gen-z-translator]
square = 
long = 

[genai-by-meta]
square = 
long = 

[gencraft]
square = 
long = 

[genei]
square = 
long = 

[genera-so]
square = 
long = 

[generai]
square = 
long = 

[generatebg]
square = 
long = 

[generatext]
square = 
long = 

[generative-bi]
square = 
long = 

[generative-press]
square = 
long = 

[generator-xyz]
square = 
long = 

[genesis-therapeutics]
square = 
long = 

[genia]
square = 
long = 

[genie]
square = 
long = 

[genie-ai]
square = 
long = 

[geniea]
square = 
long = 

[genieai]
square = 
long = 

[genius-ai]
square = 
long = 

[genius-chatbot]
square = 
long = 

[genius-pdf]
square = 
long = 

[genius-title]
square = 
long = 

[genius-trip]
square = 
long = 

[geniusreview]
square = 
long = 

[geniusui]
square = 
long = 

[genji]
square = 
long = 

[genmo]
square = 
long = 

[genome]
square = 
long = 

[genpictures]
square = 
long = 

[gentext-ai-assistant]
square = 
long = 

[gentlegossip]
square = 
long = 

[gentrace]
square = 
long = 

[genusoft]
square = 
long = 

[genworlds]
square = 
long = 

[genzart]
square = 
long = 

[geppettochat]
square = 
long = 

[gerev]
square = 
long = 

[gerwin]
square = 
long = 

[gestualy]
square = 
long = 

[getactyv]
square = 
long = 

[getaiway]
square = 
long = 

[getbetterpics]
square = 
long = 

[getbot]
square = 
long = 

[getbotz]
square = 
long = 

[getbuddies]
square = 
long = 

[getchatgpt]
square = 
long = 

[getcustomer]
square = 
long = 

[getdone]
square = 
long = 

[getfloorplan]
square = 
long = 

[getgenie]
square = 
long = 

[getimg-ai]
square = 
long = 

[getitout]
square = 
long = 

[getlogit]
square = 
long = 

[getmails]
square = 
long = 

[getmax]
square = 
long = 

[getme-flights]
square = 
long = 

[getodata]
square = 
long = 

[getonboard]
square = 
long = 

[getsound-ai]
square = 
long = 

[getsummary-tech]
square = 
long = 

[ggpredict]
square = 
long = 

[ghengis-khan-chatbot]
square = 
long = 

[ghola]
square = 
long = 

[ghostcut]
square = 
long = 

[ghostposts-ai]
square = 
long = 

[ghostwrite]
square = 
long = 

[ghostwriter]
square = 
long = 

[ghostwriter-by-youai]
square = 
long = 

[ghostwrites]
square = 
long = 

[ghostwryter]
square = 
long = 

[gibbly]
square = 
long = 

[gienjibot]
square = 
long = 

[gifstar]
square = 
long = 

[gift-box]
square = 
long = 

[gift-genie]
square = 
long = 

[gift-matchr]
square = 
long = 

[giftadvisor]
square = 
long = 

[giftassistant]
square = 
long = 

[giftastic-ai]
square = 
long = 

[giftbot]
square = 
long = 

[gifter]
square = 
long = 

[giftgpt]
square = 
long = 

[gifthat]
square = 
long = 

[gifthuntr]
square = 
long = 

[giftideas-app]
square = 
long = 

[giftideasai]
square = 
long = 

[giftit]
square = 
long = 

[giftl]
square = 
long = 

[giftlist-genie]
square = 
long = 

[giftocadabra]
square = 
long = 

[giftruly]
square = 
long = 

[gifts-genie]
square = 
long = 

[giftwrap]
square = 
long = 

[giga-brain]
square = 
long = 

[gignite]
square = 
long = 

[gimme-summary-ai]
square = 
long = 

[ginimachine]
square = 
long = 

[giotto]
square = 
long = 

[gipy]
square = 
long = 

[gist-ai]
square = 
long = 

[gistai]
square = 
long = 

[gistreader]
square = 
long = 

[gistty]
square = 
long = 

[gistvid]
square = 
long = 

[git18n]
square = 
long = 

[gita-ai]
square = 
long = 

[gitbook]
square = 
long = 

[gitgab]
square = 
long = 

[github-copilot]
square = 
long = 

[github-copilot-x]
square = 
long = 

[gitlab-code-suggestions]
square = 
long = 

[gitpoet]
square = 
long = 

[gitsnag]
square = 
long = 

[gitsul-group]
square = 
long = 

[gitterbot]
square = 
long = 

[gitwit]
square = 
long = 

[gitya]
square = 
long = 

[giveflag]
square = 
long = 

[gizmo]
square = 
long = 

[gizzmo]
square = 
long = 

[gladia]
square = 
long = 

[gladly-sidekick]
square = 
long = 

[glaive]
square = 
long = 

[glambase]
square = 
long = 

[glasgowgpt]
square = 
long = 

[glasp]
square = 
long = 

[glasp-co]
square = 
long = 

[glass-health]
square = 
long = 

[glasses-gone]
square = 
long = 

[glazegpt]
square = 
long = 

[glean]
square = 
long = 

[gleek]
square = 
long = 

[gliastudio]
square = 
long = 

[glide-apps]
square = 
long = 

[glif-app]
square = 
long = 

[gliglish]
square = 
long = 

[glimmer]
square = 
long = 

[glimpse]
square = 
long = 

[glimpsehere]
square = 
long = 

[gling]
square = 
long = 

[glivia]
square = 
long = 

[globalgpt]
square = 
long = 

[globalthreat-inc]
square = 
long = 

[glossai]
square = 
long = 

[glov]
square = 
long = 

[glow-ai]
square = 
long = 

[glowbom]
square = 
long = 

[glows]
square = 
long = 

[glowup-ai]
square = 
long = 

[gltr]
square = 
long = 

[gluecharm]
square = 
long = 

[glyf]
square = 
long = 

[glyf-space]
square = 
long = 

[gmailgpt]
square = 
long = 

[gnbly]
square = 
long = 

[gnius]
square = 
long = 

[gnod]
square = 
long = 

[goafterwork]
square = 
long = 

[goastvs]
square = 
long = 

[god-in-a-box]
square = 
long = 

[godmode]
square = 
long = 

[goemailtracker]
square = 
long = 

[gogptgo]
square = 
long = 

[gold-retriever]
square = 
long = 

[golem]
square = 
long = 

[goless]
square = 
long = 

[golinks]
square = 
long = 

[gombwe]
square = 
long = 

[gong-engage]
square = 
long = 

[good-tripper-guide]
square = 
long = 

[goodboai]
square = 
long = 

[goodhues]
square = 
long = 

[goodlisten]
square = 
long = 

[goodlookup]
square = 
long = 

[goodmeetings]
square = 
long = 

[goodnightreader]
square = 
long = 

[goodvision]
square = 
long = 

[goodwork]
square = 
long = 

[gooey-ai]
square = 
long = 

[google-labs]
square = 
long = 

[google-search-labs]
square = 
long = 

[google-sge]
square = 
long = 

[google-text-to-speech]
square = 
long = 

[googpt]
square = 
long = 

[gooseai]
square = 
long = 

[gordon-post]
square = 
long = 

[gordon-ramsai]
square = 
long = 

[gorilla-terminal]
square = 
long = 

[gotely]
square = 
long = 

[gotomarket-ai]
square = 
long = 

[governgpt]
square = 
long = 

[gowhisper]
square = 
long = 

[gozen]
square = 
long = 

[gpt]
square = 
long = 

[gpt-2-output-detector]
square = 
long = 

[gpt-4]
square = 
long = 

[gpt-4-consulting]
square = 
long = 

[gpt-adblocker]
square = 
long = 

[gpt-assist]
square = 
long = 

[gpt-baker]
square = 
long = 

[gpt-beaver]
square = 
long = 

[gpt-book-club]
square = 
long = 

[gpt-calculator]
square = 
long = 

[gpt-chatbot]
square = 
long = 

[gpt-for-sheets]
square = 
long = 

[gpt-games]
square = 
long = 

[gpt-gifts]
square = 
long = 

[gpt-grammarly]
square = 
long = 

[gpt-help]
square = 
long = 

[gpt-hotline]
square = 
long = 

[gpt-lab]
square = 
long = 

[gpt-law]
square = 
long = 

[gpt-mate]
square = 
long = 

[gpt-me]
square = 
long = 

[gpt-movie-recommender]
square = 
long = 

[gpt-persona]
square = 
long = 

[gpt-ppt]
square = 
long = 

[gpt-prompt-engineer]
square = 
long = 

[gpt-quickbar]
square = 
long = 

[gpt-reviews]
square = 
long = 

[gpt-sidepanel]
square = 
long = 

[gpt-sms]
square = 
long = 

[gpt-stick]
square = 
long = 

[gpt-stylist]
square = 
long = 

[gpt-tab]
square = 
long = 

[gpt-trainer]
square = 
long = 

[gpt-unbound]
square = 
long = 

[gpt-vetting]
square = 
long = 

[gpt-virtual-assistant]
square = 
long = 

[gpt-workspace]
square = 
long = 

[gpt3-text-generator]
square = 
long = 

[gpt4autocoder]
square = 
long = 

[gpt4free]
square = 
long = 

[gpt4office]
square = 
long = 

[gpt6-ai]
square = 
long = 

[gpt95]
square = 
long = 

[gptagent]
square = 
long = 

[gptanywhere]
square = 
long = 

[gptassistant]
square = 
long = 

[gptbots]
square = 
long = 

[gptbricks]
square = 
long = 

[gptchat]
square = 
long = 

[gptconsole]
square = 
long = 

[gptea]
square = 
long = 

[gpteammate]
square = 
long = 

[gpteverywhere]
square = 
long = 

[gptflow]
square = 
long = 

[gptform]
square = 
long = 

[gptfriend]
square = 
long = 

[gptfy]
square = 
long = 

[gptgame]
square = 
long = 

[gptgo]
square = 
long = 

[gptgo-extension]
square = 
long = 

[gptify]
square = 
long = 

[gptkit]
square = 
long = 

[gptmagicprompts]
square = 
long = 

[gptmate]
square = 
long = 

[gptmyday]
square = 
long = 

[gptnext]
square = 
long = 

[gptocr]
square = 
long = 

[gptpress]
square = 
long = 

[gptrim]
square = 
long = 

[gptsafe]
square = 
long = 

[gptservice]
square = 
long = 

[gptsuite]
square = 
long = 

[gptweet]
square = 
long = 

[gptzero]
square = 
long = 

[gpurich]
square = 
long = 

[gradienmood]
square = 
long = 

[gradient-ai]
square = 
long = 

[gradientj]
square = 
long = 

[gradio]
square = 
long = 

[grafi-ai]
square = 
long = 

[graft]
square = 
long = 

[graham-ai]
square = 
long = 

[grain]
square = 
long = 

[gramara]
square = 
long = 

[grambotplus]
square = 
long = 

[grammar-ai]
square = 
long = 

[grammar-gpt]
square = 
long = 

[grammarbot]
square = 
long = 

[grammarguru]
square = 
long = 

[granica]
square = 
long = 

[grant-ai]
square = 
long = 

[grantable]
square = 
long = 

[grantboost]
square = 
long = 

[grapegpt]
square = 
long = 

[graphic-ai]
square = 
long = 

[graphlit]
square = 
long = 

[graphqlai]
square = 
long = 

[graphy-app]
square = 
long = 

[graviti-diffus]
square = 
long = 

[gravitywrite]
square = 
long = 

[graxle]
square = 
long = 

[graydient]
square = 
long = 

[great-headlines]
square = 
long = 

[greatfit]
square = 
long = 

[green-room-ai]
square = 
long = 

[green-screen-ai]
square = 
long = 

[greenlite]
square = 
long = 

[greenthumb]
square = 
long = 

[greetai-co]
square = 
long = 

[greip]
square = 
long = 

[gremi]
square = 
long = 

[grep-help]
square = 
long = 

[gretel]
square = 
long = 

[greynights]
square = 
long = 

[grid-2-0]
square = 
long = 

[grit-io]
square = 
long = 

[grocer-ai]
square = 
long = 

[grok]
square = 
long = 

[groopub]
square = 
long = 

[groupthink]
square = 
long = 

[growthbar]
square = 
long = 

[growthsense]
square = 
long = 

[grro]
square = 
long = 

[gstudio]
square = 
long = 

[gueno]
square = 
long = 

[guestlab]
square = 
long = 

[guidde]
square = 
long = 

[guide-ai]
square = 
long = 

[guided]
square = 
long = 

[guidefai]
square = 
long = 

[guidenco]
square = 
long = 

[guidie]
square = 
long = 

[gummy-search]
square = 
long = 

[guru]
square = 
long = 

[gustavosta-magicprompt]
square = 
long = 

[gym-genie]
square = 
long = 

[gymbuddy]
square = 
long = 

[gamelight-ai-backed-mobile-marketing]
square = 
long = 

[ganogram]
square = 
long = 

[getresponse]
square = 
long = 

[gnorman]
square = 
long = 

[goalsgpt]
square = 
long = 

[goatchat]
square = 
long = 

[godchat]
square = 
long = 

[gosearch]
square = 
long = 

[gpt-commands]
square = 
long = 

[gpt-driver]
square = 
long = 

[gptinf]
square = 
long = 

[grapha-ai]
square = 
long = 

[gtan-chat]
square = 
long = 

[geniepm]
square = 
long = 

[gpt-ez]
square = 
long = 

[genvid]
square = 
long = 

[gopdf-10339]
square = 
long = 

[gptmatch-me]
square = 
long = 

[gptexcel]
square = 
long = 

[gigapixel-ai]
square = 
long = 

[goaiadapt]
square = 
long = 

[gpt-prompt-tuner]
square = 
long = 

[grammarly]
square = 
long = 

[goelo]
square = 
long = 

[gpt-for-work]
square = 
long = 

[gpt-clone]
square = 
long = 

[gopilotx]
square = 
long = 

[girlfriendgpt]
square = 
long = 

[gista]
square = 
long = 

[generative-engine]
square = 
long = 

[godelbots]
square = 
long = 

[galadon]
square = 
long = 

[gpt-for-me]
square = 
long = 

[gpt-marketer]
square = 
long = 

[genesi-ai]
square = 
long = 

[genie-by-lumalabs]
square = 
long = 

[gemini-by-google]
square = 
long = 

[ghostthewriter]
square = 
long = 

[gpt4-vision-chatbot]
square = 
long = 

[glorify]
square = 
long = 

[generated-photos]
square = 
long = 

[getzing]
square = 
long = 

[ghostbuster-app]
square = 
long = 

[gnothi]
square = 
long = 

