name: Run update.py on commit

on:
  push:
    branches:
      - main

jobs:
  run-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run update.py
      run: python3 update.py
